# Function Transformer

This notebook will cover using Function Transformers to specify custom transformations, this is applicable when we want to transform our data using a custom function. We will first start with a toy dataset which has postive, negative and zero values. 

In [1]:
import numpy as np
import pandas as pd

import math

from sklearn.preprocessing import FunctionTransformer

In [2]:
arr = np.array([[0, -1], 
                [-6, 7]])
arr

array([[ 0, -1],
       [-6,  7]])

The function transformer performs the transformation of our choice, we pass it as an input parameter

In [3]:
abs_transformer = FunctionTransformer(np.abs, validate=False)

abs_transformer.transform(arr)

array([[0, 1],
       [6, 7]])

In [4]:
def calculate_squares(x):
    return x * x

In [5]:
squares_transformer = FunctionTransformer(calculate_squares, validate=False)

squares_arr = squares_transformer.transform(arr)

squares_arr

array([[ 0,  1],
       [36, 49]])

In [6]:
inverse_transformer = FunctionTransformer(inverse_func=np.sqrt, validate=False)

inverse_transformer

FunctionTransformer(accept_sparse=False, check_inverse=True, func=None,
                    inv_kw_args=None, inverse_func=<ufunc 'sqrt'>, kw_args=None,
                    validate=False)

In [7]:
orig_arr = inverse_transformer.inverse_transform(squares_arr)

orig_arr

array([[0., 1.],
       [6., 7.]])